### ISSUE TITLE
The RteCtrl command turns the relay off v0.7.3

### ISSUE THREAD

**Issue by Pokisiekk** [3mdeb/meta-rte#24]
**meta-rte version**
v0.7.3

**Affected component(s) or functionality**
relay control

**Brief summary**
Entering the command `RteCtrl` or `RteCtrl [any_tekst_not_starting_from _'-']` turns the relay off

**How reproducible**
100%

**How to reproduce**

1. Turn on relay
2. Run the command `RteCtrl` or `RteCtrl [any_tekst_not_starting_from _'-']`

**Expected behavior**
`-sh: RteCtrl: command not found` or something similar - the command should not perform any operations

**Actual behavior**
The relay is turned off

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by sulewskiprzemyslaw** [comment]
@Pokisiekk This is not the bug - `RteCtrl` is the instance for RTE API and should be present in this OS. 

Please don't use it. If you need to control the GPIO or relay, please use the built-in script `rte_ctrl`.
