### ISSUE TITLE
Please include cpu in meta-rte release

### ISSUE THREAD

**Issue by macpijan** [3mdeb/meta-rte#29]
**The problem you're addressing (if any)**

Using custom software/scripts on RTE is problematic:
- I need to send it to RTE first
- RTE must have correct versions of libraries etc

**Describe the solution you'd like**

- easily run my own software scripts from my PC directly on RTE
- please include [cpu](https://github.com/u-root/cpu)

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Comment by PLangowski** [comment]
@macpijan Do i understand correctly that only the `cpud` binary is required on RTE? This binary starts the ssh server, to which you can connect from your host PC with the `cpu` command.
Also, is it enough to just provide the binary to the image or should it be configured as a service/daemon?

**Comment by PLangowski** [comment]
@macpijan Could you test if it works properly in [v0.7.4-rc5](https://github.com/3mdeb/meta-rte/releases/tag/v0.7.4-rc5)?

**Comment by PLangowski** [comment]
@macpijan Have you tested it? If not, maybe you can tell me how to do it and I will test it myself?

**Comment by macpijan** [comment]
I have never used `cpu` myself, because it was not available on RTE :upside_down_face: 

Supposedly, it should allow you to run some scripts or application from local PC on the RTE, without actually copying it on the RTE.

Probably just go through the https://archive.fosdem.org/2022/schedule/event/plan_9_cpu_cmd/ or other talk or documentation from: https://github.com/u-root/cpu#talks

Can cpu daemon be started on RTE? I'm not sure if we have all the kernel requirements enabled.

**Comment by PLangowski** [comment]
@macpijan `cpu` has been tested and added as part of the [v0.7.4](https://github.com/3mdeb/meta-rte/releases/tag/v0.7.4) release. Please refer to the  [cpu example usage document](https://github.com/3mdeb/meta-rte/blob/v0.7.4/docs/cpu.md).  With this I think we can close this issue.
