### ISSUE TITLE
Please include vim or vim-tiny at least

### ISSUE THREAD

**Issue by macpijan** [3mdeb/meta-rte#30]
**The problem you're addressing (if any)**

Cirrently shipped `vi` is very limited

**Describe the solution you'd like**

Having `vim` with much more options allows to more easily edit files on the RTE

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Comment by PLangowski** [comment]
@macpijan I created a PR that adds vim. I could not test it due to the problem I am experiencing with building the packagergroup recipe, but it's a pretty straightforward change.
