### ISSUE TITLE
kas-docker installation steps in README are outdated

### ISSUE THREAD

**Issue by mkopec** [3mdeb/meta-rte#34]
**meta-rte version**

n/a

**Affected component(s) or functionality**

README

**Brief summary**

The README contains an instruction to execute the following command:

```
wget -O ~/bin/kas-docker https://raw.githubusercontent.com/siemens/kas/master/kas-docker
```

However, the URL points to a symlink to `kas-container` - therefore this will fail on a system where kas-container isn't already installed (only the symlink will be downloaded)

**How reproducible**

100%

**How to reproduce**

1. Follow the readme's `kas-docker` installation steps

**Expected behavior**

kas-docker is installed

**Actual behavior**

kas-docker is not installed

**Screenshots**

n/a

**Additional context**

n/a

**Solutions you've tried**

using kas from my distro's repos

**Comment by PLangowski** [comment]
@mkopec Should the URL point to `kas-container` instead? Then maybe the whole README should be updated so that it mentions `kas-container` and not `kas-docker`?

**Comment by macpijan** [comment]
Precisely
