### ISSUE TITLE
tmux is not usable

### ISSUE THREAD

**Issue by pietrushnic** [3mdeb/meta-rte#63]
```bash
root@rte:~# tmux new
open terminal failed: missing or unsuitable terminal: tmux-256color
```

there should be also test added to avoid issue in future

```bash
root@rte:~# cat /etc/issue
RTE (Remote Test Environment Distro) 0.7.4 \n \l
```

**Comment by pietrushnic** [comment]
```
root@rte:~# minicom -D /dev/ttyS1 -b 115200
No termcap entry for tmux-256color
```

**Comment by macpijan** [comment]
It must be on your side, we use it all the time. Quickly verified and works on APU2 and APU3 RTEs you have checked out.

**Comment by pietrushnic** [comment]
very weird, fact is I'm using minimalistics xterm, so maybe that is an issue

**Comment by macpijan** [comment]
Probably something with:
```
echo $TERM
xterm-256color
```

**Comment by artur-rs** [comment]
@pietrushnic do you need any more support or should we close this one?

**Comment by pietrushnic** [comment]
No, thanks.
