### ISSUE TITLE
Can we have default minicom config integrated, that disables hardware flow control?

### ISSUE THREAD

**Issue by macpijan** [3mdeb/meta-rte#65]

**Comment by WiktorG351** [comment]
I think this should be pretty simple. I've manually made a `minicom` config file:
```
root@rte:~# cat /etc/minirc.dfl 
pu rtscts           No
root@rte:~# 
```
and that seems to do the trick (aka. hardware flow control always disabled). Ive [added a PR](https://github.com/3mdeb/meta-rte/pull/71) that adds such a file.

**Comment by artur-rs** [comment]
@tym2k1 let's integrate these changes after Scarthgap update
