### ISSUE TITLE
Integrate flash.sh script into image

### ISSUE THREAD

**Issue by macpijan** [3mdeb/meta-rte#80]
Integrate script from: https://github.com/3mdeb/RteCtrl/pull/22 into v0.8.X release

- [ ] Add recipe for `flash.sh` script to `meta-rte` and integrate it into image by default
- [ ] Remove this script from `RteCtrl`
- [ ] Scan Dasharo documentation references to `flash.sh` and remove them. Or leave a note that this `flash.sh` script is integrated on RTE OS v0.8.x or higher if needed, depending on the found case.
- [ ] Extend script with additional parameters/env variables, such as:
    - ability to select 1.8V vs 3.3V (currently it is hardcoded to 3.3V)
    - ability to provide some extra parameters to flashrom command (such as: `-ifd -i fd -i me -i bios`)

**Comment by macpijan** [comment]
This is designed to have some working solution in a short term.

As suggested in https://github.com/3mdeb/RteCtrl/pull/22#issue-2627579069 already, this `flash.sh` script is not a perfect approach, and we already have something better with `osfv_cli`.

This can take a bit more time to discuss and implement, that is why we have a separate ticket for it here: https://github.com/3mdeb/meta-rte/issues/82

**Comment by macpijan** [comment]
@wessel-novacustom

If you'd like to test the updated version of the script from: https://github.com/3mdeb/meta-rte/pull/83/files

The file can be downloaded here: https://raw.githubusercontent.com/3mdeb/meta-rte/c4c0f2b6c947061defa1b83bd585745ec0ecadb6/recipes-go/3mdeb-rtectrl/3mdeb-rtectrl/flash.sh

**Comment by macpijan** [comment]
@wessel-novacustom did you have a chance to test this?

**Comment by wessel-novacustom** [comment]
> @wessel-novacustom did you have a chance to test this?

Not yet, I will do so on Saturday.

**Comment by wessel-novacustom** [comment]
@macpijan 

> flashrom -p "$FLASHROM_PROGRAMMER" "$FLASHROM_PARAMS"

Is wrong.

It results in:

> root@rte:~# ./flash.sh -V 3.3V probe
Setting SPI VCC to 3.3V
SPI lines ON
SPI Vcc ON
Probing ...
flashrom 1.4.0 on Linux 6.6.28 (armv7l)
flashrom is free software, get the source code at https://flashrom.org
>
> Error: Extra parameter found.
Please run "flashrom --help" for usage info.
SPI Vcc OFF
SPI lines OFF

---------

The fix would be:

> flashrom -p "$FLASHROM_PROGRAMMER" $FLASHROM_PARAMS

So without the double quotes for the flashrom params.

---------

I just made that change and tried:

root@rte:~# ./flash.sh -V 3.3V probe --flashrom-params "-o output.txt"

And that generated the output.txt file correctly, meaning that the flashrom params are still working, while now also without flashrom params.

**Comment by macpijan** [comment]
@DaniilKl

**Comment by DaniilKl** [comment]
Fixed, more inf. in linked PR
